# Generated by Django 4.2.6 on 2023-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitemingredient_menuitem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
