# Generated by Django 4.2.6 on 2023-10-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_menuitem_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price_per_unit',
        ),
        migrations.DeleteModel(
            name='RecipeRequirement',
        ),
    ]
