# Generated by Django 4.2.6 on 2023-10-18 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_finalorder_finalordermenuitem_draftorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MenuItemIngredient',
            new_name='RecipeRequirement',
        ),
        migrations.DeleteModel(
            name='BusinessConfig',
        ),
        migrations.RemoveField(
            model_name='finalordermenuitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='finalordermenuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='order',
        ),
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='quantity_required',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='DraftOrder',
        ),
        migrations.DeleteModel(
            name='FinalOrder',
        ),
        migrations.DeleteModel(
            name='FinalOrderMenuItem',
        ),
        migrations.DeleteModel(
            name='OrderMenuItem',
        ),
        migrations.AddField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
    ]
